[project]
name = "promplate-py-docs"
version = "1"
authors = [{ name = "Muspi Merol", email = "me@promplate.dev" }]
dependencies = [
    "mkdocs>=1.5.3",
    "mkdocs-material>=9.5.7",
    "brotli>=1.1.0",
    "minify-html>=0.15.0",
]
requires-python = ">=3.8"
license = { text = "MIT" }

[tool.pdm]
distribution = false

[tool.pdm.scripts]
dev = "mkdocs serve --dirtyreload"
minify = { call = "minify:main" }
inject = { call = "inject:main" }
gen = { composite = ["inject", "mkdocs build", "minify"] }
